from pydantic import BaseModel, Field
from typing import Optional, List

class ChatRequest(BaseModel):
    """
    Defines the shape of a request to the /chat endpoint.
    """
    question: str = Field(..., min_length=1, description="The question asked by the user.")
    context: Optional[str] = Field(None, description="Optional text selected by the user to narrow the focus.")

class SourceNode(BaseModel):
    """
    Defines the shape of a retrieved source node from the vector database.
    """
    id: str
    text: str
    score: float
    metadata: dict = {}

class ChatResponse(BaseModel):
    """
    Defines the shape of a response from the /chat endpoint.
    """
    answer: str = Field(..., description="The answer generated by the LLM.")
    source_nodes: Optional[List[SourceNode]] = Field(None, description="A list of content nodes used as context.")
